---
version: "3.8"
services:
  movies:
    image: arjun6074/movies:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: arjun6074/train:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: arjun6074recharge:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: arjun6074/dth:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
